### ISSUE TITLE
Incorrect handling static method arguments in ruby

### ISSUE THREAD

**Issue by sharipov-ru** [PeterRincker/vim-argumentative#8]
vim-argumentative works great for instance methods in ruby:

![test1](https://cloud.githubusercontent.com/assets/482566/3025950/ad0c432c-e00c-11e3-8912-2938efd4ecb2.gif)

but it fails to swap arguments for static (class) methods (prefixed with self) - overall string gets broken:
![test2](https://cloud.githubusercontent.com/assets/482566/3025961/ca1e35b0-e00c-11e3-8523-6afe9d63c480.gif)

ps. I'm using default plugin settings / vundle package manager and running on VIM 7.4.52

**Comment by PeterRincker** [comment]
Good catch. Thank you. I have adjusted the regex that is used to determine implicit function arguments for ruby. Please review branch [issue-8](https://github.com/PeterRincker/vim-argumentative/tree/issue-8) and let me know if it works correctly for you.

**Comment by mateusmedeiros** [comment]
I also had that problem, and your solution seems to work alright.

Please merge the branch with branch master. I'll send a PR (it's kinda cheating because it's your own commit :dancer: ) just in case you find it easier to accept it. You can ignore/refuse it and do the merge yourself of your own branch if you prefer it, but either way, please put that on master :smiley:
